// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmbTrWXabb1Z3UYGNTpJ1EMAlIu4F6AcQ',
    appId: '1:560641955294:web:edb6cf7b3bf938fe47394f',
    messagingSenderId: '560641955294',
    projectId: 'movie-57cb8',
    authDomain: 'movie-57cb8.firebaseapp.com',
    storageBucket: 'movie-57cb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZej2f9FSNxkTm5E8mExyw_oqdDew8LTE',
    appId: '1:560641955294:android:86fb7788e43efd9847394f',
    messagingSenderId: '560641955294',
    projectId: 'movie-57cb8',
    storageBucket: 'movie-57cb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7lrwLhE3bWxZMayAMZO-4hC_iYF1o_ik',
    appId: '1:560641955294:ios:d47f63c8b0d29cec47394f',
    messagingSenderId: '560641955294',
    projectId: 'movie-57cb8',
    storageBucket: 'movie-57cb8.appspot.com',
    iosBundleId: 'com.example.adminapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7lrwLhE3bWxZMayAMZO-4hC_iYF1o_ik',
    appId: '1:560641955294:ios:d47f63c8b0d29cec47394f',
    messagingSenderId: '560641955294',
    projectId: 'movie-57cb8',
    storageBucket: 'movie-57cb8.appspot.com',
    iosBundleId: 'com.example.adminapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmbTrWXabb1Z3UYGNTpJ1EMAlIu4F6AcQ',
    appId: '1:560641955294:web:33cbe46bcacfb63747394f',
    messagingSenderId: '560641955294',
    projectId: 'movie-57cb8',
    authDomain: 'movie-57cb8.firebaseapp.com',
    storageBucket: 'movie-57cb8.appspot.com',
  );
}
